### PR TITLE
Include port 16262 in docker-compose and readme according to latest updates

### PR DESCRIPTION
**Pull request by theCrius**
As mentioned here: https://github.com/Renegade-Master/zomboid-dedicated-server/issues/42

### CODE REVIEW

**Comment by Renegade-Master** [comment]
I [added some updates](https://github.com/Renegade-Master/zomboid-dedicated-server/pull/43/commits/3d421ff1f3cf7fb74fc03db0a21575467d126299) to hopefully align with how Servers are supposed to be configured in the most recent version of the game.

I hope you don't mind me just committing to your PR.

**Comment by Renegade-Master** [comment]
Also, do you (@theCrius) know if the 8766 Port has been deprecated? It doesn't appear to be in the ZomboidServer.ini file anymore. The only ports are for RCON, and the two UDP Ports.

**Review by Renegade-Master — APPROVED** [review]

**Comment by theCrius** [comment]
All good @Renegade-Master. unfortunately I don't know about port 8766. I'm currently running this PR on my server and everything seems working. We can go ahead for me, it's your repo :)

**Comment by Renegade-Master** [comment]
#43 released as a part of [v2.2.0](https://github.com/Renegade-Master/zomboid-dedicated-server/releases/tag/v2.2.0)

**Pull request merged**
